export {
  archiveService,
  createOffer,
  createOfferGroup,
  createSchedule,
  createService,
  getAdminService,
  getAdminServices,
  getAdminTeachers,
  removeOffer,
  removeOfferGroup,
  removeSchedule,
  restoreService,
  updateOffer,
  updateOfferGroup,
  updateSchedule,
  updateService,
} from './api/admin-service';
export type {
  AdminServicesQuery,
  OfferGroupValues,
  OfferValues,
  ScheduleValues,
  ServiceValues,
} from './api/admin-service';
